export { createShellStore, prompterGlassIsStale, useAudioMeterFrame, useShellSnapshot } from "./store/createShellStore";
export type { ShellStoreOptions } from "./store/createShellStore";
export { EVENT_DOMAIN_REFRESH } from "./store/domainRefresh";
export type { DomainKey } from "./store/domainRefresh";
export {
  AUDIO_FADER_UNITY,
  FADER_MAX_DB,
  FADER_OFF_DB,
  FADER_POSITION_STEPS,
  faderDbIsOff,
  faderDbToLin,
  faderLinToDb,
} from "./audio/faderCurve";
export { positionAt, speedAt, wordsAdvanced } from "./prompter/motion";
export { anchorOrder, type AnchorOrder } from "./prompter/anchorOrder";
export { anchorArrival, noteAnchorArrival } from "./prompter/anchorArrival";
export type { PrompterMotion, PrompterMotionAnchor } from "./prompter/motion";
export { EngineRequestError } from "./transports/engineRequestError";
export { createTauriGlassLink, glassLinkOver, PROMPTER_WINDOW_LABEL } from "./transports/glassLink";
export type { GlassLink } from "./transports/glassLink";
export type {
  PictureCamera,
  PicturePlaces,
  PicturePlacesSink,
  PictureTakes,
  PicturesLink,
  PlaceRect,
  PlacedPicture,
} from "./transports/picturesLink";
export {
  FRAME_HEADER_LEN,
  FULL_PICTURE,
  SMALL_PICTURE,
  readFrames,
  testCardUyvy,
  uyvyToRgba,
  writeFrame,
} from "./transports/pictureFrame";
export type { FrameFormat, PictureFrame } from "./transports/pictureFrame";
export { createTauriTransport } from "./transports/tauriTransport";
export type {
  CommissioningCheckRequest,
  CommissioningCheckTarget,
  CommissioningStage,
  CommissioningUpdateRequest,
  EngineLaunchInfo,
  EngineTransport,
  FixtureCameraSeed,
  FixtureCameraValuesSeed,
  FixtureCamerasSeed,
  FixturePrompterScriptSeed,
  FixturePrompterSeed,
  FixtureScenario,
  AudioClipClearRequest,
  AudioMeterEntry,
  AudioMeterFrame,
  BackgroundFailure,
  CameraAutoRequest,
  CameraFormatRequest,
  CameraLookRequest,
  CameraNumber,
  CameraPressSetting,
  CameraSetRequest,
  CameraSetupUpdateRequest,
  CameraStepRequest,
  LightingPaletteApplyRequest,
  LightingPaletteCreateRequest,
  LightingPaletteUpdateRequest,
  PrompterJumpRequest,
  PrompterLayoutReportRequest,
  PrompterLookUpdateRequest,
  PrompterPasteConvertResult,
  PrompterPasteRequest,
  PrompterScriptImportRequest,
  PrompterSpeedRequest,
  PrompterTextSizeRequest,
  RecoveryState,
  RunnerStage,
  ShellState,
  ShellTalentMark,
  ShellStore,
  SetupSection,
  StartupFailure,
  WorkspaceId,
} from "./types";
export { EVENT_NAMES, PROTOCOL_VERSION, REQUEST_METHODS, STARTUP_LIFECYCLE_STATES } from "./generated/protocol";
export type {
  EventEnvelope,
  EventName,
  JsonObject,
  JsonValue,
  RequestEnvelope,
  RequestMethod,
  ResponseEnvelope,
  StartupLifecycleState,
} from "./generated/protocol";
// Generated by `npm run protocol:generate` (ts-rs under the
// `studio-control-engine/ts-rs` cargo feature). Do not hand-edit; the
// `protocol:check` lane catches drift.
export type { AudioChannelSnapshot } from "./generated/snapshots/AudioChannelSnapshot";
export type { AudioCapabilitySnapshot } from "./generated/snapshots/AudioCapabilitySnapshot";
export type { AudioConsoleSnapshotSlot } from "./generated/snapshots/AudioConsoleSnapshotSlot";
export type { AudioConsoleSnapshots } from "./generated/snapshots/AudioConsoleSnapshots";
export type { AudioMixTargetSnapshot } from "./generated/snapshots/AudioMixTargetSnapshot";
export type { AudioSnapshot } from "./generated/snapshots/AudioSnapshot";
export type { CameraAutos } from "./generated/snapshots/CameraAutos";
export type { CameraChoice } from "./generated/snapshots/CameraChoice";
export type { CameraHealthEntry } from "./generated/snapshots/CameraHealthEntry";
export type { CameraLevel } from "./generated/snapshots/CameraLevel";
export type { CameraLink } from "./generated/snapshots/CameraLink";
export type { CameraPicture } from "./generated/snapshots/CameraPicture";
export type { CameraDialBank } from "./generated/snapshots/CameraDialBank";
export type { CameraDials } from "./generated/snapshots/CameraDials";
export type { CameraRecentAction } from "./generated/snapshots/CameraRecentAction";
export type { CameraRecording } from "./generated/snapshots/CameraRecording";
export type { CameraSetupSummary } from "./generated/snapshots/CameraSetupSummary";
export type { CameraSnapshot } from "./generated/snapshots/CameraSnapshot";
export type { CameraState } from "./generated/snapshots/CameraState";
export type { CameraSwitch } from "./generated/snapshots/CameraSwitch";
export type { CameraTone } from "./generated/snapshots/CameraTone";
export type { CameraUnavailable } from "./generated/snapshots/CameraUnavailable";
export type { CameraValues } from "./generated/snapshots/CameraValues";
export type { CamerasHealthCheck } from "./generated/snapshots/CamerasHealthCheck";
export type { CamerasPictures } from "./generated/snapshots/CamerasPictures";
export type { CamerasSnapshot } from "./generated/snapshots/CamerasSnapshot";
export type { PictureState } from "./generated/snapshots/PictureState";
export type { LightingDmxChannelSnapshot } from "./generated/snapshots/LightingDmxChannelSnapshot";
export type { LightingDmxMonitorSnapshot } from "./generated/snapshots/LightingDmxMonitorSnapshot";
export type { LightingEffect } from "./generated/snapshots/LightingEffect";
export type { LightingFixtureCatalogSnapshot } from "./generated/snapshots/LightingFixtureCatalogSnapshot";
export type { LightingFixtureChannelRangeSnapshot } from "./generated/snapshots/LightingFixtureChannelRangeSnapshot";
export type { LightingFixtureChannelSnapshot } from "./generated/snapshots/LightingFixtureChannelSnapshot";
export type { LightingFixtureControlOptionSnapshot } from "./generated/snapshots/LightingFixtureControlOptionSnapshot";
export type { LightingFixtureControlSnapshot } from "./generated/snapshots/LightingFixtureControlSnapshot";
export type { LightingFixtureDefinitionSnapshot } from "./generated/snapshots/LightingFixtureDefinitionSnapshot";
export type { LightingFixtureEmitterLayoutSnapshot } from "./generated/snapshots/LightingFixtureEmitterLayoutSnapshot";
export type { LightingFixtureModeSnapshot } from "./generated/snapshots/LightingFixtureModeSnapshot";
export type { LightingFixtureOutputSnapshot } from "./generated/snapshots/LightingFixtureOutputSnapshot";
export type { LightingFixturePhotometricSampleSnapshot } from "./generated/snapshots/LightingFixturePhotometricSampleSnapshot";
export type { LightingFixturePixelLayoutSnapshot } from "./generated/snapshots/LightingFixturePixelLayoutSnapshot";
export type { LightingFixtureSnapshot } from "./generated/snapshots/LightingFixtureSnapshot";
export type { LightingFixtureVisualSnapshot } from "./generated/snapshots/LightingFixtureVisualSnapshot";
export type { LightingGroupSnapshot } from "./generated/snapshots/LightingGroupSnapshot";
export type { LightingPaletteKind } from "./generated/snapshots/LightingPaletteKind";
export type { LightingPaletteSnapshot } from "./generated/snapshots/LightingPaletteSnapshot";
export type { LightingSceneFixtureSnapshot } from "./generated/snapshots/LightingSceneFixtureSnapshot";
export type { LightingSceneSnapshot } from "./generated/snapshots/LightingSceneSnapshot";
export type { LightingSnapshot } from "./generated/snapshots/LightingSnapshot";
export type { LightingSpatialMarker } from "./generated/snapshots/LightingSpatialMarker";
export type { PrompterAnchor } from "./generated/snapshots/PrompterAnchor";
export type { PrompterCue } from "./generated/snapshots/PrompterCue";
export type { PrompterGlassSnapshot } from "./generated/snapshots/PrompterGlassSnapshot";
export type { PrompterGlassSummary } from "./generated/snapshots/PrompterGlassSummary";
export type { PrompterLayoutLine } from "./generated/snapshots/PrompterLayoutLine";
export type { PrompterLook } from "./generated/snapshots/PrompterLook";
export type { PrompterParagraph } from "./generated/snapshots/PrompterParagraph";
export type { PrompterPlace } from "./generated/snapshots/PrompterPlace";
export type { PrompterRun } from "./generated/snapshots/PrompterRun";
export type { PrompterScriptSnapshot } from "./generated/snapshots/PrompterScriptSnapshot";
export type { PrompterScriptSummary } from "./generated/snapshots/PrompterScriptSummary";
export type { PrompterScreenState } from "./generated/snapshots/PrompterScreenState";
export type { PrompterScreenSummary } from "./generated/snapshots/PrompterScreenSummary";
export type { PrompterHealthCheck } from "./generated/snapshots/PrompterHealthCheck";
export type { PrompterCheckTone } from "./generated/snapshots/PrompterCheckTone";
export type { PrompterSnapshot } from "./generated/snapshots/PrompterSnapshot";
export type { PrompterTextColour } from "./generated/snapshots/PrompterTextColour";
export type { PrompterVersionSummary } from "./generated/snapshots/PrompterVersionSummary";
